# Generated by Django 6.0.2 on 2026-04-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='day',
            field=models.CharField(choices=[('weekdays', 'Weekdays'), ('weekends', 'Weekends')], max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_range',
            field=models.CharField(choices=[('1', '₺'), ('2', '₺₺'), ('3', '₺₺₺')], default='2', max_length=1),
        ),
    ]
