# Generated by Django 6.0.2 on 2026-04-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0008_restaurantphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="e.g., Starters, Main Course, Dessert",
                max_length=50,
            ),
        ),
    ]
