# Generated by Django 6.0.4 on 2026-04-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='google_maps_embed_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
