# Generated by Django 6.0.2 on 2026-04-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0010_restaurant_google_maps_embed_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="google_maps_embed_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
