# Generated by Django 6.0.2 on 2026-05-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0012_reviewlike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openinghours",
            name="day",
            field=models.CharField(
                choices=[
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                    ("saturday", "Saturday"),
                    ("sunday", "Sunday"),
                ],
                max_length=20,
            ),
        ),
    ]
