# Generated by Django 6.0.2 on 2026-05-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0014_split_grouped_opening_hours"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="openinghours",
            options={},
        ),
    ]
